version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: wallet_manager_postgres
    environment:
      POSTGRES_DB: wallet_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallet_manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data: